Code/Web/GestionDeProyectos/apps/core/urls.py
from django.urls import path
from apps.core.views import InicioView,GestionView,FormatosView,TableroView

app_name="core"

urlpatterns = [
    path("", InicioView.as_view(),name="inicio"),
    path("gestion/", GestionView.as_view(),name="gestion"),
    path("formatos/", FormatosView.as_view(),name="formatos"),
    path("tablero/", TableroView.as_view(),name="tablero"),
]

Code/Web/GestionDeProyectos/apps/cuentas/urls.py
from django.urls import path
from .views import RegistroViews
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

from .views import CustomPasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
app_name="cuentas"

urlpatterns = [
    path('registro/',RegistroViews.as_view(),name="registro"),
    path('cambiar-contraseña/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('cambiar-contraseña/hecho/', PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'
    ), name='password_change_done'),
]

Code/Web/GestionDeProyectos/apps/publicaciones/urls.py
from django.urls import path
from .views import PublicacionDeleteView, PublicacionViews,PublicacionDetailView,PublicacionCreateView,PublicacionUpdateView

app_name="publicacion"

urlpatterns = [
    path("", PublicacionViews.as_view(),name="inicio"),
    path("<int:pk>/", PublicacionDetailView.as_view(),name="detalle"),
    path("crear/", PublicacionCreateView.as_view(),name="crear"),
    path("<int:pk>/editar", PublicacionUpdateView.as_view(),name="editar"),
    path("<int:pk>/eliminar", PublicacionDeleteView.as_view(),name="eliminar"),

]

Code/Web/GestionDeProyectos/gs_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include('django.contrib.auth.urls'),name="login"),
    path("",include("apps.core.urls"), name="core"),
    path("cuentas/",include("apps.cuentas.urls"), name="cuentas"),
    path("publicaciones/",include("apps.publicaciones.urls"), name="publicaciones"),
]

Code/Web/GestionDeProyectos/apps/core/models.py
from django.db import models

# Create your models here.

Code/Web/GestionDeProyectos/apps/cuentas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class UsuarioPersonalizado(AbstractUser):
    edad=models.PositiveIntegerField(null=True,blank=True)

Code/Web/GestionDeProyectos/apps/publicaciones/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

class Publicacion(models.Model):
    titulo=models.CharField(max_length=255)
    texto=models.TextField()
    fecha=models.DateTimeField(auto_now_add=True)
    autor=models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    
    def __str__(self):
        return self.titulo[:50]
    
    def get_absolute_url(self):
        return reverse("publicacion:detalle",args=[str(self.id)])
    
class Comentario(models.Model):
    publicacion=models.ForeignKey(Publicacion,on_delete=models.CASCADE, related_name="comentarios")
    comentario=models.CharField(max_length=255)
    autor=models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comentario
    
    def get_absolute_url(self):
        return reverse("publicacion:inicio")
    

Code/Web/GestionDeProyectos/apps/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UsuarioPersonalizado

class UsuarioPersonalizadoCrearForm(UserCreationForm):
    class Meta(UserCreationForm):
        model=UsuarioPersonalizado
        fields=UserCreationForm.Meta.fields+('username','email','edad',)
        

class UsuarioPersonalizadoEditarForm(UserChangeForm):
    class Meta:
        model=UsuarioPersonalizado
        fields=UserChangeForm.Meta.fields
        

Code/Web/GestionDeProyectos/apps/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

"""
Clase InicioView
Redirecciona a la pagina de inicio principal de la aplicacion
"""
class InicioView(TemplateView):
    template_name="core/index.html"
    

"""
Clase GestionView
Redirecciona a la pagina de gestion de proyectos, usuarios y demas
"""
class GestionView(TemplateView):
    template_name="core/gestion.html"


"""
Clase FormatosView
Redirecciona a la pagina de formatos (SRs, HU, Diccionario de datos, etc.)
"""
class FormatosView(TemplateView):
    template_name="core/formatos.html"


"""
Clase TableroView
Redirecciona a la pagina donde esta el tablero de quehaceres
"""
class TableroView(TemplateView):
    template_name="core/tablero.html"

Code/Web/GestionDeProyectos/apps/cuentas/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UsuarioPersonalizadoCrearForm

class RegistroViews(CreateView):
    form_class=UsuarioPersonalizadoCrearForm
    success_url=reverse_lazy('login')
    template_name="registration/registro.html"
    
# views.py
# views.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'password_change_form.html'
    success_url = reverse_lazy('registro')

Code/Web/GestionDeProyectos/apps/publicaciones/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Publicacion


class PublicacionViews(LoginRequiredMixin,ListView):
    model=Publicacion
    template_name="publicacion/index.html"
    context_object_name="publicaciones"
    
    
class PublicacionDetailView(DetailView):
    model=Publicacion
    template_name="publicacion/detalle.html"
    context_object_name="publicacion_detalle"
    
class PublicacionCreateView(LoginRequiredMixin,CreateView):
    model=Publicacion
    template_name="publicacion/crear.html"
    fields=["titulo","texto"]
    
    def form_valid(self,form):
        form.instance.autor=self.request.user
        return super().form_valid(form)
    
    
class PublicacionUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=Publicacion
    template_name="publicacion/editar.html"
    fields=["titulo","texto"]
    
    def test_func(self):
        obj=self.get_object()
        return obj.autor==self.request.user
    
    
class PublicacionDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model=Publicacion
    template_name="publicacion/eliminar.html"
    success_url=reverse_lazy("publicacion:inicio")
    
    def test_func(self):
        obj=self.get_object()
        return obj.autor==self.request.user

Code/Web/GestionDeProyectos/templates/base/body.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock titulo %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/iconos.js' %}" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

</head>
<body>

    <div class="wrapper">
        {% include "base/sidebar.html" %}

        <div class="main">
            <nav class="navbar navbar-expand px-3 border-bottom navColor">
                <!-- Button for sidebar toggle -->
                <button class="btn" type="button" data-bs-theme="dark">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </nav>
            <main class="content px-3 py-2">
               

                {% if user.is_authenticated %}
                <div class="alert alert-success" role="alert">
                    <p><i class="fas fa-check-circle"></i> Bienvenido <strong>{{ user.username }}</strong></p>
                </div>
                {% else %}
                <div class="alert alert-danger" role="alert">
                    <p><i class="fas fa-exclamation-circle"></i> No estás logueado</p>

                </div>
                {% endif %}


                <div class="container-fluid">
                    {% block contenido %}
                    {% endblock contenido %}
                </div>
            </main>
          </div>

    </div>

  


    <!-- Bootstrap JS y dependencias -->
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>

</body>
</html>

Code/Web/GestionDeProyectos/templates/base/footer.html
<footer>
    <p>&copy; 2024 DaromanX. Todos los derechos reservados.</p>
</footer>

Code/Web/GestionDeProyectos/templates/base/sidebar.html
<!-- Sidebar -->
<aside id="sidebar">
    <div class="h-100 sidebarColor" >
        <div class="sidebar-logo">
            <a href="{% url "core:inicio" %}">DaromanX</a>
        </div>
        <!-- Sidebar Navigation -->
        <ul class="sidebar-nav">
            <li class="sidebar-header">
                Tools & Components
            </li>
            <li class="sidebar-item">
                <a href="{% url "publicacion:inicio" %}" class="sidebar-link">
                    <i class="fa-solid fa-newspaper"></i>
                    Publicaciones
                </a>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link">
                    <i class="fa-solid fa-list pe-2"></i>
                    Perfil
                </a>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#pages"
                    aria-expanded="false" aria-controls="pages">
                    <i class="fa-regular fa-file-lines pe-2"></i>
                    Paginas
                </a>
                <ul id="pages" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Analytics</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Ecommerce</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Crypto</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard"
                    aria-expanded="false" aria-controls="dashboard">
                    <i class="fa-solid fa-sliders pe-2"></i>
                    Dashboard
                </a>
                <ul id="dashboard" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Dashboard Analytics</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Dashboard Ecommerce</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#auth"
                    aria-expanded="false" aria-controls="auth">
                    <i class="fa-regular fa-user pe-2"></i>
                    Cuenta
                </a>
                <ul id="auth" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="{% url "login" %}" class="sidebar-link">Login</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url "cuentas:registro" %}" class="sidebar-link">Registro</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="sidebar-item">
                        <a href="{% url "password_change" %}" class="sidebar-link">Cambiar contraseña</a>
                    </li>
                    
                    {% endif %}
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link" id="logout-link">
                            Cerrar Sesión
                        </a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-header">
                Multi Level Nav
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#multi"
                    aria-expanded="false" aria-controls="multi">
                    <i class="fa-solid fa-share-nodes pe-2"></i>
                    Multi Level
                </a>
                <ul id="multi" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse"
                            data-bs-target="#multi-two" aria-expanded="false" aria-controls="multi-two">
                            Two Links
                        </a>
                        <ul id="multi-two" class="sidebar-dropdown list-unstyled collapse">
                            <li class="sidebar-item">
                                <a href="#" class="sidebar-link">Link 1</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="#" class="sidebar-link">Link 2</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</aside>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var logoutLink = document.getElementById('logout-link');
    
        logoutLink.addEventListener('click', function(event) {
            event.preventDefault();
    
            var form = document.createElement('form');
            form.action = "{% url 'logout' %}";
            form.method = 'POST';
            form.style.display = 'none';  // Ocultar el formulario
    
            var csrfToken = document.createElement('input');
            csrfToken.type = 'hidden';
            csrfToken.name = 'csrfmiddlewaretoken';
            csrfToken.value = "{{ csrf_token }}";  // Agregar el token CSRF
    
            form.appendChild(csrfToken);
            document.body.appendChild(form);
    
            form.submit();
        });
    });
    </script>

Code/Web/GestionDeProyectos/templates/core/formatos.html
{% extends "base/body.html" %}
{% block titulo %} Formatos {% endblock titulo %}

{% block contenido %}
<center><h2>Formatos</h2></center>
{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/core/gestion.html
{% extends "base/body.html" %}
{% block titulo %} Gestion {% endblock titulo %}

{% block contenido %}
<center><h2>Gestion</h2></center>
{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/core/index.html
{% extends "base/body.html" %}
{% block titulo %} Inicio {% endblock titulo %}

{% block contenido %}
<center><h2>Inicio</h2></center>
{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/core/tablero.html
{% extends "base/body.html" %}
{% block titulo %} Tablero {% endblock titulo %}

{% block contenido %}
<center><h2>Tableros</h2></center>
{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/publicacion/crear.html
{% extends "base/body.html" %}
{% load crispy_forms_tags %}

{% block titulo %} Crear Publicacion {% endblock titulo %}

{% block contenido %}
<br>
<center><h2>Crear nueva publicacion </h2></center>
<br>

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'publicacion:inicio'  %}" class="btn btn-secondary btn-custom">
                    <i class="fas fa-arrow-left"></i> Volver
                </a>
                <button type="submit" class="btn btn-primary btn-custom">
                    <i class="fas fa-save"></i> Guardar
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/publicacion/detalle.html
{% extends "base/body.html" %}
{% block titulo %} Detalle Publicaciones {% endblock titulo %}

{% block contenido %}
<br>
<center><h2>Detalle de la publicacion </h2></center>
<br>

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h3 style="color: black;"><span>{{ publicacion_detalle.titulo }}</span></h3>
                <div>
                    <a href="{% url 'publicacion:inicio'  %}" class="btn btn-secondary btn-custom">
                        <i class="fas fa-arrow-left"></i> Volver
                    </a>
                    <a href="{% url 'publicacion:eliminar' publicacion_detalle.id %}" class="btn btn-danger btn-custom">
                        <i class="fas fa-trash-alt"></i> Eliminar Publicación
                    </a>
                    <a href="{% url 'publicacion:editar' publicacion_detalle.id %}" class="btn btn-warning btn-custom">
                        <i class="fas fa-edit"></i> Editar Publicación
                    </a>
                </div>
            </div>
            <p class="lead text-justify">{{ publicacion_detalle.texto }}</p>
        </div>
    </div>
</div>

{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/publicacion/editar.html
{% extends "base/body.html" %}
{% load crispy_forms_tags %}

{% block titulo %} Editar publicacion {% endblock titulo %}

{% block contenido %}
<br>
<center><h2>Editar de la publicacion </h2></center>
<br>

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'publicacion:detalle' publicacion.id %}" class="btn btn-secondary btn-custom">
                    <i class="fas fa-arrow-left"></i> Cancelar
                </a>
                <button type="submit" class="btn btn-primary btn-custom">
                    <i class="fas fa-save"></i> Actualizar
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/publicacion/eliminar.html
{% extends "base/body.html" %}
{% block titulo %} Eliminar Publicaciones {% endblock titulo %}

{% block contenido %}
<br>
<center><h2>Eliminar la publicacion </h2></center>
<br>

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <p class="confirmation-message">¿Estás seguro que deseas eliminar "<span>{{ publicacion.titulo }}</span>"?</p>
                <div class="d-flex justify-content-between">
                    <a href="{% url 'publicacion:detalle' publicacion.id %}" class="btn btn-secondary btn-custom">
                        <i class="fas fa-arrow-left"></i> Cancelar
                    </a>
                    <button type="submit" class="btn btn-danger btn-custom">
                        <i class="fas fa-trash-alt"></i> Eliminar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

Code/Web/GestionDeProyectos/templates/publicacion/index.html
{% extends "base/body.html" %}
{% block titulo %} Publicaciones {% endblock titulo %}

{% block contenido %}
<br>
<center><h2>Publicaciones</h2></center>

<!-- Tu contenido -->

<a href="#" data-toggle="modal" data-target="#passwordChangeModal" id="change-password-link">Modal cambio de contraseña</a>

<!-- Modal -->
<div class="modal fade" id="passwordChangeModal" tabindex="-1" role="dialog" aria-labelledby="passwordChangeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="passwordChangeModalLabel">Cambio de Contraseña</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="passwordChangeFormContainer">
                    <!-- El formulario se cargará aquí -->
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Cargar el formulario de cambio de contraseña en el modal al hacer clic en el enlace
    document.getElementById('change-password-link').addEventListener('click', function() {
        $('#passwordChangeFormContainer').load("{% url 'password_change' %} form");
    });
</script>
<br>
<div class="container mt-4">
    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'publicacion:crear' %}" class="btn btn-success">
            <i class="fas fa-plus"></i> Crear Nuevo
        </a>
    </div>

    {% for publicacion in publicaciones %}
        <div class="card mb-3 shadow-sm border-0">
            <div class="card-header d-flex justify-content-between bg-primary text-white">
                <span style="text-transform: uppercase;"><strong>{{ publicacion.autor }}</strong></span>
                <span>{{ publicacion.fecha }}</span>
            </div>

            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'publicacion:detalle' publicacion.id %}" class="text-decoration-none text-dark">{{ publicacion.titulo }}</a>
                </h5>
                {% with words=publicacion.texto|truncatewords_html:50 %}
                    <p class="card-text">{{ words }}</p>
                {% endwith %}
            </div>

            <div class="card-footer bg-light">
                <h6 class="mb-3"><i class="fas fa-comments"></i> Comentarios</h6>
                {% for comentario in publicacion.comentarios.all %}
                    <div class="media mb-3 p-3 border rounded bg-white shadow-sm">
                         <div class="media-body">
                            <h6 class="mt-0 text-primary">{{ comentario.autor }}</h6>
                            <p>{{ comentario }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


{% endblock contenido %}